### ISSUE TITLE
How to retrieve all interpolated points

### ISSUE THREAD

**Issue by XuanLin** [orbingol/NURBS-Python_Examples#1]
Hi,

How to I retrieve the values of interpolated points? It looks like there is no Curve.evalpts property, which the Curve.evaluate() function should store them at.

Thanks!

**Comment by XuanLin** [comment]
Actually I found it to be Curve._curve_points.

**Comment by orbingol** [comment]
@XuanLin curve points can be retrieved via `Curve.curvepts` and surface points via `Surface.surfpts`. With the release of v4.0, there exists a new property `evalpts` which is a replacement of `curvepts` and `surfpts`. They still work, though but `evalpts` is intended to unify the getter function of the evaluated points.  I have ported `evalpts` property to v3.x series. Please do a pip upgrade to get the latest version.

Variables starting with underscores are considered as private/protected variables in python and they should only be used if you are extending the library. Otherwise, I would recommend you to use the properties.
